### ISSUE TITLE
some suggestion and package upgrades.

### ISSUE THREAD

**Issue by bobyuancn** [whamtet/ctmx-demo#2]
The ctmx dependency (hiccup) hasn't updated since Jan 22, 2019, not sure if its still active developed, no other mature alternative?

Why not upgrade Bootstrap to latest v5.2?

ctmx is still using Bootstrap 4.5.3. 
The last Bootstrap previous release v4.6 is here:
https://getbootstrap.com/docs/4.6/getting-started/introduction/

From above Bootstrap documentation, the script html tags (jquery,bootstrap) are before `</body>` tag, not just before `</html>`. Is this a defect?

In ctmx-demo README.md, it is using an old name "clj-htmx", maybe it need to be replaced with "ctmx"?

Some dependencies are also need to upgrade, such as:
* luminus template, latest version is v4.47, in ctmx-demo README.md it is said using v3.88
* java-time, https://github.com/dm3/clojure.java-time/tags
* nrepl
any many others...

Hope you consider. Thanks!

**Comment by whamtet** [comment]
Thanks @bobyuancn I've recently decided to replace this demo with a kit based alternative which is easier to update.  Kit has a very nice modules system and uses `deps.edn` which can require github repositories directly rather than having to push everything to clojars.  I would greatly appreciate if you try following the new instructions in the readme and give me feedback on that new demo instead.
